package com.example.mealplanner.utils

import android.content.Context
import android.net.Uri
import com.example.mealplanner.data.Meal
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.lang.StringBuilder

object CsvExporter {
    fun exportMealsToCsv(context: Context, uri: Uri, meals: List<Meal>) {
        context.contentResolver.openOutputStream(uri)?.use { outputStream ->
            OutputStreamWriter(outputStream).use { writer ->
                // Header
                writer.write("ID,Name,Ingredients\n")
                
                // Data
                meals.forEach { meal ->
                    val escapedName = escapeCsv(meal.name)
                    val escapedIngredients = escapeCsv(meal.ingredients.joinToString(", "))
                    writer.write("${meal.id},$escapedName,$escapedIngredients\n")
                }
            }
        }
    }

    fun importMealsFromCsv(context: Context, uri: Uri): List<Meal> {
        val importedMeals = mutableListOf<Meal>()
        context.contentResolver.openInputStream(uri)?.use { inputStream ->
            BufferedReader(InputStreamReader(inputStream)).use { reader ->
                val header = reader.readLine() // Skip header
                var line: String? = reader.readLine()
                while (line != null) {
                    val parts = parseCsvLine(line)
                    if (parts.size >= 3) {
                        val name = parts[1]
                        val ingredientsStr = parts[2]
                        val ingredients = ingredientsStr.split(",").map { it.trim() }.filter { it.isNotEmpty() }
                        // ID is ignored as it will be auto-generated by Room
                        importedMeals.add(Meal(name = name, ingredients = ingredients))
                    }
                    line = reader.readLine()
                }
            }
        }
        return importedMeals
    }

    private fun escapeCsv(value: String): String {
        return if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            "\"${value.replace("\"", "\"\"")}\""
        } else {
            value
        }
    }

    private fun parseCsvLine(line: String): List<String> {
        val result = mutableListOf<String>()
        var current = StringBuilder()
        var inQuotes = false
        var i = 0
        while (i < line.length) {
            val c = line[i]
            if (c == '\"') {
                if (inQuotes && i + 1 < line.length && line[i + 1] == '\"') {
                    current.append('\"')
                    i++
                } else {
                    inQuotes = !inQuotes
                }
            } else if (c == ',' && !inQuotes) {
                result.add(current.toString())
                current = StringBuilder()
            } else {
                current.append(c)
            }
            i++
        }
        result.add(current.toString())
        return result
    }
}
